### PR TITLE
Odiumediae grammar changes

### PR DESCRIPTION
**Pull request by ghost**
Changed the wording to make a better impression :)

### CODE REVIEW

**Comment by rse** [comment]
I'm not a native English speaker, but is "what cleaner" really correct? The "what" at least confuses me here. I still would expect "how". So, would be "See how cleaner and more concise..." also correct?

**Comment by ghost** [comment]
Yes, it’s correct.

It’s either "what something looks like" or "how something looks." So as an alternative you could indeed write "See how cleaner and more concise …", if you drop the superfluous "like".

I don’t want to appear too nit-picky, but I am also natively a German speaker.

**Comment by rse** [comment]
Ok, text changed. Thanks for the feedback.

**Comment by ghost** [comment]
No problem. Nice project and overview!

**Pull request closed without merging**
